export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_ERROR = 'LOGGED_ERROR'
export const LOGGED_OUT = 'LOGGED_OUT'
export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_PROJECT_DETAIL = 'SET_PROJECT_DETAIL'
export const CLEAR_PROJECT_DETAIL = 'CLEAR_PROJECT_DETAIL'

export const SET_PATENT_DETAIL = 'SET_PATENT_DETAIL'
export const CLEAR_PATENT_DETAIL = 'CLEAR_PATENT_DETAIL'

export const SET_TALENT_INFO = 'SET_TALENT_INFO'
export const CLEAR_TALENT_INFO = 'CLEAR_TALENT_INFO'

export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE'
export const SET_SEARCH_CONDITION = 'SET_SEARCH_CONDITION'
export const SET_SEARCH_PAGE = 'SET_SEARCH_PAGE'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
export const SET_SEARCH_RESULT_COUNT = 'SET_SEARCH_RESULT_COUNT'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
