export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_ERROR = 'LOGGED_ERROR'
export const LOGGED_OUT = 'LOGGED_OUT'
export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_PROJECT_DETAIL = 'SET_PROJECT_DETAIL'
export const CLEAR_PROJECT_DETAIL = 'CLEAR_PROJECT_DETAIL'

export const SET_PATENT_DETAIL = 'SET_PATENT_DETAIL'
export const CLEAR_PATENT_DETAIL = 'CLEAR_PATENT_DETAIL'
